# See https://github.com/actions/labeler

'🚨 action':
  - .github/workflows/**

'🌏 i18n':
  - docs/en/**/*

'📚 docs':
  - docs/**
  
'✒️ documentation':
  - 'README.md'
  
'🚧 astro':
  - 'starlight/astro.config.mjs'
  
'📀 assets':
  - starlight/src/assets/**
  - starlight/public/**
  
'📦 package':
  - 'starlight/package.json'
