# See https://github.com/actions/labeler

'🚨 action':
  - .github/workflows/**

'📚 content':
  - starlight/src/content/docs/**
  
'🌏 i18n':
  - starlight/src/content/docs/en/**

'✒️ documentation':
  - '**/README.md'
  
'🚧 astro':
  - 'starlight/astro.config.mjs'
  
'📀 assets':
  - starlight/src/assets/**
  - starlight/public/**
  
'📦 package':
  - 'starlight/package.json'
