name: Docker Image Push

on:
  push:
    branches: [main]
  merge_group:
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: docker.io
  IMAGE_NAME: trueberryless/mutanuq
  NODE_VERSION: 18

jobs:  
  docker-push-image:
    if: contains(github.event.head_commit.message, 'version') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest  
    permissions:
      contents: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build and Push to Docker Hub
        uses: trueberryless-org/version-build-push-docker-action@v1.0.0
        with:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
